### DISCUSSION TITLE
Alt servers

### DISCUSSION THREAD

**Discussion by nathanchu** [anuraghazra/github-readme-stats#685] [General]
The main github readme stats server went down with 402 Payment Required today (as you probably know). This has happened multiple times and I have a proposed solution. I'd be happy to host an alternate server for this purpose, assuming it doesn't get too much traffic. I'd like to hear your thoughts on this @anuraghazra, and whether anyone else would consider hosting a community alt server.

**Comment by anuraghazra** [comment]
@nathanchu hmm thats a really nice suggestion.

So what do you propose? we will gather few people who are willing to deploy github-readme-stats to their vercel instance and we will use those URLs to use as alternatives?

**Reply by nathanchu** [reply]
Yes, pretty much. I was also considering writing a self hosted github action for this, it wouldn't be too hard to mock req and res for what they're used for.

**Reply by anuraghazra** [reply]
> I was also considering writing a self hosted github action for this, it wouldn't be too hard to mock req and res for what they're used for.

Huh i'm curious, self hosted gh action? can you explain what would we do with that?

**Reply by nathanchu** [reply]
```yaml
name: github-readme-stats
on:
  schedule:
    - cron: "0 * * * *"
jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
    - uses: anuraghazra/github-readme-stats@action
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        path: "assets/stats.svg"
        params: "?username=anuraghazra"
```
something like this ^
